spring:
  application:
    name: application

   rabbitmq:
      host: 192.168.99.100
      port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env: gagaxiao


